package:
  name: allclear
  version: 0.1

source:
  path: .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - torch
    - rasterio
    - numpy
    - matplotlib
    - pandas

about:
  home: https://github.com/Zhou-Hangyu/allclear
  license: MIT
  summary: 'A comprehensive benchmark for cloud removal.'